FROM openjdk:12-alpine

LABEL author="Achim Wiedemann"
LABEL description="Image with Otto Challenge Spring App"

ADD otto-challenge-spring-0.0.1-SNAPSHOT.jar /

CMD ["java", "-jar", "otto-challenge-spring-0.0.1-SNAPSHOT.jar"]